services:
  navidrome:
    container_name: ctr-navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - "4533:4533"
    volumes:
      - ./navidrome:/data
      - ./music:/music:ro # Remove if you want to use external storage
      #- str:/music:ro # If you want to use external storage
    networks:
      navidrome:
        ipv4_address: 10.1.34.2

networks:
  navidrome:
    name: net-navidrome
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.34.0/24
         gateway: 10.1.34.1

#volumes:
#  str:
#    driver: local
#    driver_opts:
#      type: cifs
#      device: "//host/share"
#      o: "username=username,password=password,uid=1000,gid=1000"