services:
  arcane:
    container_name: ctr-arcane
    image: ghcr.io/getarcaneapp/arcane
    restart: unless-stopped
    env_file: .env
    #ports:
    #  - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/app/data
      #- ./projects:/app/data/projects
    networks:
      arcane:
        ipv4_address: 10.1.32.2

networks:
  arcane:
    name: net-arcane
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.32.0/24
         gateway: 10.1.32.1