services:
  server:
    container_name: ctr-authentik-server
    image: ghcr.io/goauthentik/server:2025.10.1
    restart: unless-stopped
    command: server
    env_file: .env
    #user: root # This should fix permission denied errors
    #ports:
    #  - "9000:9000"
    #  - "9443:9443"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    networks:
      authentik:
        ipv4_address: 10.1.11.2

  worker:
    container_name: ctr-authentik-worker
    image: ghcr.io/goauthentik/server:2025.10.1
    restart: unless-stopped
    command: worker
    env_file: .env
    #user: root # This should fix permission denied errors
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    networks:
      authentik:
        ipv4_address: 10.1.11.3

  postgresql:
    container_name: ctr-authentik-postgresql
    image: postgres:16-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      authentik:
        ipv4_address: 10.1.11.4

networks:
  authentik:
    name: net-authentik
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.11.0/24
         gateway: 10.1.11.1